# Individual classes
cis5550.flame.Coordinator=DEBUG
cis5550.flame.Worker=DEBUG
cis5550.kvs.Coordinator=DEBUG
cis5550.kvs.Worker=DEBUG
cis5550.jobs.Crawler=DEBUG
cis5550.tools.CrawlerLogger=DEBUG

# Package-level
cis5550.flame=DEBUG
cis5550.kvs=DEBUG
cis5550.jobs=DEBUG
cis5550.tools=DEBUG

# Default for everything else
cis5550=DEBUG